# Generated by Django 2.1.1 on 2018-09-10 05:57

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='tag',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
    ]
