# Generated by Django 2.1.1 on 2018-09-11 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_portfolio_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='githublink',
            field=models.URLField(blank=True, null=True, verbose_name='Github URL'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='servicelink',
            field=models.URLField(blank=True, null=True, verbose_name='Service URL'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio-img'),
        ),
    ]
